name: Update startups data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 6" # At 00:00 on Saturday.

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          yarn --frozen-lockfile
          node scripts/build-flare.js > src/startups.json
          sed -ri "s/<div id=\"updated_at\">[^<]+<\/div>/<div id=\"updated_at\">Mise Ã  jour le : $(date '+%d\/%m\/%Y %H:%M')<\/div>/" index.html
          cat index.html
      - uses: EndBug/add-and-commit@v7
        with:
          add: '["src/startups.json", "index.html"]'
          author_name: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          author_email: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          message: "chore: startups update"
